var GAME_LEVELS = [
  ["  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  x           v                                     v                        x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                           ****                           x  ",
   "  x                                                        ###               x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                     yyyyy    o      o                    x  ",
   "  x                                              x      x            o o o   x  ",
   "  x                  o   p                       x!!!!!!x                    x  ",
   "  x                               o              xxxxxxxx                    x  ",
   "  x                                                                 yyyyyyy  x  ",
   "  x                #####        yyyyy                                        x  ",
   "  x                                                   o                      x  ",
   "  x                                     o                     yyyy           x  ",
   "  x       o                            yyyy           q                      x  ",
   "  x  @                                                                       x  ",
   "  xxxxxxxxxx     xx************                                  xxxxxxxxxxxxx  ",
   "           x     x            x                 ****######*      x              ",
   "           x!!!!!x            x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x              ",
   "           x!!!!!x            x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x              ",
   "           xxxxxxx            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx              ",
   "                                                                                ",
   "                                                                                "],
   ["!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "      x    x     x  o         v                                                 ",
    "      x @  x     x                                                              ",
    "      x    x     x                                                              ",
    "      x    x     x                                                              ",
    "      x    x     x ####                                                         ",
    "      x    x     x                                                              ",
    "      x    x     x      ####  v                                                 ",
    "      x    x     x                                                              ",
    "      x    x     x                                         ****************     ",
    "      x    x     x yyyy                                                   x     ",
    "  xxxxx    xxxxxxx                                   o                    x  o  ",
    "  x o      x                                                              x     ",
    "  x        x  o         yyyy                         *                    x     ",
    "  xxxxx    x                                                              x     ",
    "      x    xxxxxxx                                                        x     ",
    "      x            yyyy                          o                        x  o  ",
    "      x                                                                   x     ",
    "      x    xxxxxxx                       o      **                        x     ",
    "      x    x     x      yyyy                                              x     ",
    "      x    x     x                      ##                                x  o  ",
    "      x    x     x                         o                              x     ",
    "      x    x     x yyyy                                                   x     ",
    "      x b  x     x                o        *                              x     ",
    "      x    x     x                                                        x  o  ",
    "      x    x     x                *                                       x     ",
    "      xxxxxx     x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "                                                                                ",
    "                                                                                "],
    ["  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
     "  x      v      v     v     v     v     v     v             x           x  ",
     "  x                                                         x           x  ",
     "  x                                                         x           x  ",
     "  x                                                         x           x  ",
     "  x                                                         x           x  ",
     "  x                                                         x           x  ",
     "  x                                                 d       x           x  ",
     "  x  @                                                      x           x  ",
     "  xxxxx*******************************************          x           x  ",
     "  x                     x       x       x       x           x           x  ",
     "  x                     x       x       x       x           x           x  ",
     "  x                     x       x       x       x           x       o   x  ",
     "  x                  o  x   o   x   o       o       o       x           x  ",
     "  x                  x      x       x       x       x       x     o   o x  ",
     "  x                  x      x       x       x       x       x           x  ",
     "  x                  x      x       x       x       x       x           x  ",
     "  x                  x      x       x       x       x       x           x  ",
     "  x             *****xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           x  ",
     "  x                                                              xxxxxxxx  ",
     "  x                                                              x      x  ",
     "  x    ###                                                       x  r   x  ",
     "  x                                                           xxxx      x  ",
     "  x                        o                                  x  x      x  ",
     "  x                       yyyy                                x  x      x  ",
     "  x                                                        xxxx  x   o  x  ",
     "  x o           yyyy                        yyyy           x     x      x  ",
     "  x***                                                     x     x o   ox  ",
     "  x                                                        x     x      x  ",
     "  x    *****                    ********                   x     x      x  ",
     "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxx  ",
     "                                                                            ",
     "                                                                            "],
     ["  x                                                      x  ",
      "  x                                                      x  ",
      "  x                                                      x  ",
      "  x                                                      x  ",
      "  x                                                      x  ",
      "  x                                                      x  ",
      "  x                                                      x  ",
      "  x      x   x   x    x   x    x   x  x  x   x  x        x  ",
      "  x       xox   x x   x   x    x   x  x  xxoox  x        x  ",
      "  x        x   x   x  x   x    x o x  x  x x x  x        x  ",
      "  x        x    x x   xooox    xoxox  x  x  xx           x  ",
      "  x        x     x    xxxxx     x x   x  x   x  x        x  ",
      "  x                                                      x  ",
      "  x  @                                                   x  ",
      "  xxxxxx*********************************************xxxxx  ",
      "                                                            "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
